name: Lint

on:
  push:
    branches: [dev]
    paths:
      - 'ovos_hardware_helpers/**'
      - 'test/**'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [dev]
    paths:
      - 'ovos_hardware_helpers/**'
      - 'test/**'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

jobs:
  lint:
    uses: OpenVoiceOS/gh-automations/.github/workflows/lint.yml@dev
    secrets: inherit
    with:
      ruff: true
      ruff_args: '.'
      pre_commit: false
      pr_comment: true
